version: '3.3'
services:
  library-db:
    image: mysql:latest
#    build: .
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_DATABASE: 'library'
    ports:
      - '3308:3306'

  eureka-server:
    build: ./eureka-server/
#      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - library-network

  book-service:
    build: ./book-service/
#      dockerfile: book-service/Dockerfile
    ports:
      - "5555:5555"
    expose:
      - 5555
    networks:
      - library-network
    depends_on:
      - library-db

  user-service:
    build: ./user-service/
#      dockerfile: user-service/Dockerfile
    ports:
      - "5551:5551"
    expose:
      - 5551
    networks:
      - library-network
    depends_on:
      - library-db

  book-assign-service:
    build: ./book-assign-service/
#      dockerfile: book-assign-service/Dockerfile
    ports:
      - "5552:5552"
    expose:
      - 5552
    networks:
      - library-network
    depends_on:
      - library-db

networks:
  library-network:
    driver: bridge
