version: '3.3'
services:
  eureka-server:
    build: ./eureka-server/
    #      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    hostname: eureka-host
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-host
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - library-network

  book-service:
    build: ./book-service/
    #      dockerfile: book-service/Dockerfile
    container_name: book-service
    ports:
      - "5555:5555"
    expose:
      - 5555
    depends_on:
      - library-db
    links:
      - eureka-server
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://library-db:3306/library?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-host:8761/eureka
    networks:
      - library-network

  user-service:
    build: ./user-service/
    #      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "5551:5551"
    expose:
      - 5551
    depends_on:
      - library-db
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://library-db:3306/library?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - library-network

  book-assign-service:
    build: ./book-assign-service/
    #      dockerfile: book-assign-service/Dockerfile
    container_name: book-assign-service
    ports:
      - "5552:5552"
    expose:
      - 5552
    depends_on:
      - library-db
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://library-db:3306/library?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - library-network

  library-db:
    image: mysql:latest
    container_name: library-database
    restart: on-failure
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - library-network

volumes:
  db-data:

networks:
  library-network:
