version: '3.3'
services:
  eureka-server:
    build: ./eureka-server/
    container_name: discovery-server
    ports:
      - "8761:8761"

  book-service:
    build: ./book-service/
    container_name: book-service
    ports:
      - "5555:5555"
    depends_on:
      - library-db
    links:
      - eureka-server
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://library-db:3306/library?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

  user-service:
    build: ./user-service/
    container_name: user-service
    ports:
      - "5551:5551"
    depends_on:
      - library-db
    links:
      - eureka-server
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://library-db:3306/library?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

  book-assign-service:
    build: ./book-assign-service/
    container_name: book-assign-service
    ports:
      - "5552:5552"
    depends_on:
      - library-db
    links:
      - eureka-server
      - user-service
      - book-service
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://library-db:3306/library?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

  library-db:
    image: mysql:latest
    container_name: library-database
    restart: on-failure
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

