version: '3.7'
services:
  book-service-test:
    build: ./
    #      dockerfile: book-service/Dockerfile
    container_name:
    hostname:
    ports:
      - 5551:5551
    expose:
      - 5551
    networks:
      - library-network
    depends_on:
      - library-db
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://library-db:3306/library?autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&tinyInt1isBit=false&createDatabaseIfNotExist=true&useSSL=false
#      SPRING_JPA_GENERATE-DDL: true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_DATASOURCE_DRIVER_CLASS_NAME: om.mysql.cj.jdbc.Driver
      eureka.client.service-url.defaulZone=http://localhost:8761/eureka

  library-db:
    image: mysql:latest
    #    build: .
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_USER: 'root'
    ports:
      - '3308:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - library-network
volumes:
  db-data:

networks:
  library-network:
#    driver: bridge
